[project]
name = "report-llm-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "Victor Bratko",email = "bratko.viktor2004@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "langgraph (>=0.5.2,<0.6.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "langchain-openai (>=0.3.27,<0.4.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "slowapi (>=0.1.9,<0.2.0)",
    "langchain-community (>=0.3.27,<0.4.0)",
    "langchain-ollama (>=0.3.4,<0.4.0)",
    "langfuse (>=3.2.1,<4.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
